### ISSUE TITLE
Update multi-buy hint to show an example

### ISSUE THREAD

**Issue by Casperbart** [f-klubben/stregsystemet#112]
The current hint when a user buys the same thing multiple times in a row says something along the line of “psst... multi-buy is enabled”. 
This message is not very helpful for people who doesn’t know what multi-buy or quick buy is.

A suggestion to improve this is to show a context aware hint e.g. “Multi-buy is enabled. You could have typed {user} {item}:{amount}”. Where amount is the times the person bought the same item, which should be updated every time an item is bought.

**Comment by DelusionalLogic** [comment]
Queued for next release
