### ISSUE TITLE
Make enter return to frontpage after failed multibuy

### ISSUE THREAD

**Issue by fishbacon** [f-klubben/stregsystemet#119]
Currently when a multibuy fails you cannot return to the main page without using the mouse. That is not good. 

Please make it possible to return to the store page using the enter key after seeing the amazing error page.

**Comment by DelusionalLogic** [comment]
I'm pretty sure you can use the html "accesskey". In chrome and firefox you activate them by holding ```Alt+Shift+<key>```. Since the accesskey on the restart button is q that would be ```Alt+Shift+q``` to return to the main page from anywhere!

**Comment by VirtualSatai** [comment]
TAB + Enter also works

**Comment by BoAnd** [comment]
The same as #515. So I will close it.
