### ISSUE TITLE
Send email to Fember in sign-up

### ISSUE THREAD

**Issue by Rene4100** [f-klubben/stregsystemet#151]
When we are adding a new member we should send them a email such that they know when they can use their newly made account

**Comment by BoAnd** [comment]
It only needs some more code review https://github.com/f-klubben/stregsystemet/pull/152. It could be awesome to have done before next semester.

**Comment by joandrsn** [comment]
I believe that this should be closed since it was implemented with #185

**Comment by cogitantium** [comment]
I agree @joandrsn
