### ISSUE TITLE
Multibuy

### ISSUE THREAD

**Issue by DelusionalLogic** [f-klubben/stregsystemet#17]
So if we look into the code it seems like multibuy was once possible, but dropped because the sales weren't carried out as an atomic operation. You could therefore end up buying some of your multibuy product, but not all.

If we intend to allow multibuy again, we will need to make multiple sales into a single atomic operation.

**Comment by fishbacon** [comment]
I did a quick patch to make the multibuy component atomic.
See https://github.com/f-klubben/stregsystemet/commit/7f959218f0a032d7acc73e6f1160353292a9b2f0
