### ISSUE TITLE
Make functionality to contact the duks in the kiosk

### ISSUE THREAD

**Issue by ScumbagDog** [f-klubben/stregsystemet#175]
Having to sign in to your mail at your computer when the fridge is empty to send a mail to the duks is tedious. Instead, it should be possible to alert the duks when the fridge stock is low or empty.

**Comment by hrjakobsen** [comment]
The 'dukse' are free to fill the fridge when it fits their schedule. I don't think nagging them through stregsystemet is warranted.

**Comment by ScumbagDog** [comment]
We could also just sign whoever presses it up for the TREO mailing list

**Comment by hrjakobsen** [comment]
As this is not part of the core functionality of stregsystemet, I'm closing this issue.

**Comment by ScumbagDog** [comment]
That's fair
