### ISSUE TITLE
Periodical product

### ISSUE THREAD

**Issue by VirtualSatai** [f-klubben/stregsystemet#18]
Such as fadøl in foobar.

**Comment by fishbacon** [comment]
Foobar seems like a view/room (#19) and not a period. 
Which one do we think is more important and/or simpler to implement.
We do currently have a way of having a product "expire" but that seems counterproductive since it requires an admin to interact with the system before every foobar.

**Comment by DelusionalLogic** [comment]
Foobar does indeed seem more like a #19 issue. I think #19 is more immediately useful and easier to implement.

I guess something like a date for a product to be active, together with expire, could be useful for things such as flan and the various yearly events. Those aren't really "periodic" though.
