### ISSUE TITLE
requirements.txt is outdated

### ISSUE THREAD

**Issue by jenrik** [f-klubben/stregsystemet#191]
`requirements.txt` doesn't included all the required dependencies. I had to install `tox` and `pluggy` manually in order to be able to run `tox`.

**Comment by GeneralDenmark** [comment]
Overstående, men også for fabric.

**Comment by cogitantium** [comment]
Problemet med fabric er at den version vores `fabfile.py` bruger kun kører under py27

**Comment by krestenlaust** [comment]
Dette burde ikke være noget problem længere
