### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by VirtualSatai** [f-klubben/stregsystemet#20]
Django 1.11 (we run 1.10 now) is the last which will support Python 2, but it will as a LTS.

Django 2.0 and up is Python 3.x only, we should be prepared for that.

**Comment by DelusionalLogic** [comment]
I don't quite know what goes into this.

There's the 2to3 tool, which supposedly translates some of it.

Someone should feel free to look into this, as we will certainly need it sooner rather than later.

**Comment by DelusionalLogic** [comment]
I think we did it?
