### ISSUE TITLE
Stregsystemet TUI

### ISSUE THREAD

**Issue by Zaph-x** [f-klubben/stregsystemet#205]
## Motivation
No one likes GUIs or Web interfaces.
We all know the real hackerman only uses his terminal.

## Features
I therefore propose a terminal user interface, to order from stregsystemet.
This can be implemented in any language, and might need its own project.
What I envision is a console application, that makes requests to stregsystemet.
Here the user should be able to see how many stregdollars they have available, what they can buy, and even get their personalised QR code for adding more funds (Should probably be shown in the native image viewer)

**Comment by falkecarlsen** [comment]
Great job! Fixed by https://github.com/f-klubben/stregsystemet-cli

**Comment by Zaph-x** [comment]
Thank you @jones-g ! And all without any 3rd party dependencies as well, meaning a bare-bone python 3.9 will run the script just fine :wink:
