### ISSUE TITLE
Dates on user information's last 10 purchases are wrongly displayed

### ISSUE THREAD

**Issue by joandrsn** [f-klubben/stregsystemet#208]
This is a screenshot from my personal purchase history.
![image](https://user-images.githubusercontent.com/5766695/94798233-9eb32e80-03e1-11eb-8030-9a2c7832bbd2.png)

The purchases are correct, but I believe they are wrongly displayed.
I did not purchase anything at 6:30 in the morning, but rather around 8:30. I think that it is because timestamps in the databased are stored in UTC while I as a user would expect it to displayed with my local timezone (Currently CEST).

**Comment by cogitantium** [comment]
Yes, if I remember correctly all timestamps are stored in UTC **but** we've setup Django to be timezone aware which is handy.

**Comment by cogitantium** [comment]
Resolved by #211
