### ISSUE TITLE
MobilePayTool indsætter 0 payments når et payment bliver ignoreret

### ISSUE THREAD

**Issue by joandrsn** [f-klubben/stregsystemet#231]
Siden mobilepayments er blevet indført, var det nødvendigt at lave dette hack for at mails ikke blev afsendt hvis et mobilepayment blev ignoreret:
https://github.com/f-klubben/stregsystemet/blob/fbaf833a31d95fbdeb315a74a53b674d0b707a43/stregsystem/models.py#L322

Jeg tænker bare at fjerne hele `else`-blokken i dette stykke kode.
https://github.com/f-klubben/stregsystemet/blob/fbaf833a31d95fbdeb315a74a53b674d0b707a43/stregsystem/models.py#L385-L389

Payments med 0 i amount giver måske bare mere forvirring end det gavner.

Dette burde have været en del af mit PR review af #204, men det glemte jeg.

**Comment by cogitantium** [comment]
Helt enig, en anden code-smell den løsning introducerer er at jeg var nødt til at tilføje endnu et tjek ved payment save mht. mails:
https://github.com/f-klubben/stregsystemet/blob/fbaf833a31d95fbdeb315a74a53b674d0b707a43/stregsystem/models.py#L322

Indtil videre er der kun ~10 ignorerede mobilepayments i produktion som er påvirket af dette, så det vil være overkommeligt at rulle tilbage.

**Comment by falkecarlsen** [comment]
Resolved by #253

**Comment by falkecarlsen** [comment]
Not a problem to keep the `amount != 0` check although redundant.
