### ISSUE TITLE
Mobilepaytool token in production is overwritten with no content 

### ISSUE THREAD

**Issue by falkecarlsen** [f-klubben/stregsystemet#244]
Mobilepaytool stopped working sometime between now 29th of August and 20th of May. 

Turns out `tokens.json` for MobilePay API was empty and our logging for #204 was not setup sufficiently to figure out when or why.

Putting in an old token from late 2020 worked.

**Comment by joandrsn** [comment]
Non-issue.
The disk was full.

**Comment by falkecarlsen** [comment]
I hope you're right!
