### ISSUE TITLE
Implement a link for easier MobilePay payments

### ISSUE THREAD

**Issue by joandrsn** [f-klubben/stregsystemet#249]
Currently the QR codes in stregsystemet are great for fembers to add money to their account.
This does however work under the assumption that QR code is displayed on an monitor.
Currently stregsystemet is open for all on AAU's network, including members own devices. These devices may be mobile devices which have the MobilePay app installed.
As such, they may have support for directly handling a mobilepay:// url.
The system actually generates this URL in the following code:
https://github.com/f-klubben/stregsystemet/blob/7ace8fd36989f1fc225e2470f01c3d231504b30b/stregsystem/views.py#L361-L373
We could however expose this URL to the user and thus create a clickable link to create MobilePay payments.

**Comment by krestenlaust** [comment]
Hasn't this been solved by #278 (issue: #270 )?

(cc: @falkecarlsen )

**Comment by falkecarlsen** [comment]
Yes, resolved by #278
