### ISSUE TITLE
Make tilmeldings-flow for stregsystemet

### ISSUE THREAD

**Issue by falkecarlsen** [f-klubben/stregsystemet#254]
It would be nice if TREO's weren't required to manually process each new member, as they have to take into account both MobilePay backend for amount, already-taken usernames, and any missing information.

Since introducing #204 this issue becomes somewhat easier, since we can now automatically get and process optankninger, we could automagically process tilmeldinger.

One (probably not the best) approach could be:
- Make new page with modelform on Member (make check for already-taken username). Importantly still require last `n` characters of MobilePay transaction for tilmelding.
- Make cronjob which processes these tilmeldinger but only when a MobilePayment has been received with matching last `n` transaction id and sufficient amount of money.

**Comment by jonasKjellerup** [comment]
Currently working on an implementation for this. My current plan for the sign-up flow is as follows:

 1) The new user fills out a form with their user information (username, first/last name and email).
    The username and email are verified to be unique. If the information is ok we create a record
	with a unique token.
 2) We present the user with a QR-code/link for a mobilepay transaction with a per-composed description
    and amount. The description contains the aforementioned token, which is used to identify the correct transaction.
    (When doing it this way we can avoid having the user copy the last digits of the transaction id)
 3) Once the full amount has been payed, the mobilepay transaction will at some be imported at which point
    it will be scanned for the token and the user account activated.
	
As for handling the mobilepay transactions are there any preferences/guidelines for how we handle these
kind of things? E.g. an adittional cron job Vs. hooking into the existing job through an event bus or similar.

**Comment by falkecarlsen** [comment]
@jonasKjellerup sounds interesting - go for it!
Just expose a Django command, similar to how autopayment and import is implemented currently and we'll stage it in production as cronjobs. Keeping it modular also helps avoid these payment-components from breaking eachother. While having all MobilePay integration event-driven would be nice, we only pull transactions on a cronjob due to API limitations, so it really doesn't matter that subsequent modules are event-driven atm.

**Comment by jonasKjellerup** [comment]
I have a working, albeit slightly naively implemented, prototype at this point. It still needs further testing but it does seem to work as intended thus far.

> Consider modifying the Member model to contain this new data,

I ended up storing the new data in a seperate model/table (consisting of a Member reference, a token and the amount that is due to be payed). I didn't see much point in expanding the Member model since the additional information isn't relevant for existing members.

> keep in mind that the 'active' field does not entirely fit your use-case as it's for banning/no-spam etc. - not for whether the membership is paid up yet.

The prototype does currently make use of the `active` field to ensure that account can't be used until the signup has been complete. Do we have a better way of achieving a similar effect currently in the system or do we need to implement an additional system specifically for signups?

**Comment by falkecarlsen** [comment]
> active field

No problem on modelling, your approach seems better than what I suggested! I think we need to add a new bool 'paid' or similar to Member to handle this new _paid up_ logic.

If you haven't already, please fork the repo and push your work to a feature-branch - I'd love to see it. Code makes discussion easier :+1:

**Comment by jonasKjellerup** [comment]
You can find it on the `feature-signup` branch [here](https://github.com/jonasKjellerup/stregsystemet/tree/feature-signup).
