### ISSUE TITLE
Make ranking information available under 'bruger info'

### ISSUE THREAD

**Issue by falkecarlsen** [f-klubben/stregsystemet#255]
Admins have ranking available to them to see which users have bought the most/spent the most in different categories.
Some fembers would like to be able to see this information. A way to avoid GDPR issues and still give some of this information is to only show the given user their own placement in each category, e.g:

tester is:
rank 42 in forbrug
rank 3 in coffee
rank 1 in beer

This moves us forward in the fight to make stregsystem usage competitive

**Comment by joandrsn** [comment]
I like it!

**Comment by BoAnd** [comment]
I like it too. But maybe we should add **all time best in XXX**

**Comment by falkecarlsen** [comment]
> I like it too. But maybe we should add **all time best in XXX**. There is the category you're best in the whole uni time.

Oh yea, maybe both since 'Påskefrokost' as usual, and an all time best. I'm pretty certain who will _win_ the all-time beer category :sunglasses:
