### ISSUE TITLE
Quickbuy input doesn't work when returning from userinfo page

### ISSUE THREAD

**Issue by falkecarlsen** [f-klubben/stregsystemet#258]
On initial page, when inputting username, pressing enter (which lands you on the userinfo page), pressing backspace/back to return to initial page makes the input not able to submit, requiring a refresh.

**Comment by MKKlausen** [comment]
I'm not able to reproduce on my machine.
Firefox 92.0.1
Windows 10 build 19041.1237

**Comment by BoAnd** [comment]
It sounds like this problem #356.
