### ISSUE TITLE
Decimal support for QR-code generation

### ISSUE THREAD

**Issue by asger-weirsoee** [f-klubben/stregsystemet#262]
When accessing the user profile, and clicking "indsæt penge", you are provided with 4 different QR codes.
1. One for 100 kr,
2. One for previous amount of money inserted into the account
3. One for 200 kr,
4. One for userinput.

If, the previous amount of money inserted into the Stregsystem included a decimal value, the QR code generated for second one, fails to generate a valid QR code, and just fails.

The issue lies with the Danish decimal seperator "," and the English decimal seperator ".".

#QutebrowserIsBestBrowser

**Comment by Zerplin** [comment]
kan jeg hapse den her?
