### ISSUE TITLE
Make QR code always on top

### ISSUE THREAD

**Issue by Zaph-x** [f-klubben/stregsystemet#303]
Currently during April, the QR codes become un-scannable, due to overlapping imagery.
This prevents scanning of QR codes, leading to manual MP transactions, which do not contain the username of a user. A z-index attribute along with absolute positioning, could resolve this issue
![image](https://user-images.githubusercontent.com/35431127/164396811-86d450aa-bef0-484a-9760-94ffbf75e214.png)

**Comment by jonasKjellerup** [comment]
Fixed in #315
