### ISSUE TITLE
Missing back button

### ISSUE THREAD

**Issue by patrickreiffenstein** [f-klubben/stregsystemet#337]
When you go to your profile an enter the statistics page, there is no way to go back to your profile page. There is back buttons for the other sub-pages in the profile so it seems this one is just missing.

**Comment by krestenlaust** [comment]
Can confirm
**User info:**
![Screenshot of user info](https://github.com/f-klubben/stregsystemet/assets/17174333/e2094c7c-899e-47ae-9ec1-8007cf10ce03)
**Pay info:**
![Screenshot of pay](https://github.com/f-klubben/stregsystemet/assets/17174333/e76c1d09-7d13-446c-b177-9f28ba5816bc)
**Statistics page:**
![Screenshot of leaderboard screen](https://github.com/f-klubben/stregsystemet/assets/17174333/1c6e2625-5daf-486a-83fe-4a99172405a3)

Maybe there should be a common template if there isn't already, that includes the back button. The back history works though.
