### ISSUE TITLE
Multibuy enabled text showing up on user page where you can't multibuy

### ISSUE THREAD

**Issue by patrickreiffenstein** [f-klubben/stregsystemet#343]
As you can see in the picture:
![image](https://github.com/f-klubben/stregsystemet/assets/46007125/4b676dd7-a695-4a6e-8889-434492e48c7d)

When you are in the page of a user and you buy multiple items, then it tells you that multibuy is enabled and you could have typed a multibuy command, but that is only possible to do from the page where you can write the buy commands in.

**Comment by krestenlaust** [comment]
Nice catch, but duplicate of #322 😉
