### ISSUE TITLE
Migrate Purchase code from database id to one or more custom IDs

### ISSUE THREAD

**Issue by jones-g** [f-klubben/stregsystemet#35]
Previously discussed in rewrites to stregsystemet is to change the purchasing code of a product from it's database id to one or more custom but still unique IDs.

Think of them as SKU. Right now all products have a single unique SKU which is it's database id. Moving forward it would be nice if the purchase code or SKU could be changed or customized separately from bumping the database ID. F-FLAN could have 1337 then e.g. or F-LAN if we allowed alphanumeric characters.

A simple move to this should be possible simply expanding the Product model to have a relation to a SKU model and during migration simply copy each products current ID to the SKU meaning that all products would have the same purchasing code. Leaving us with the option to change or add new SKUs for products.

Would be a great feature and would still maintain old relations in sales as no actual changes are made - only where the code people type is coming from.

**Comment by krestenlaust** [comment]
I believe this was resolved in #295
