### ISSUE TITLE
Format purchase output to support duplicates (multibuy output)

### ISSUE THREAD

**Issue by krestenlaust** [f-klubben/stregsystemet#358]
`tester 1:25`:
![](https://github.com/f-klubben/stregsystemet/assets/17174333/6d4c490d-9b6e-4752-b6e8-cd10b62946bd)

`tester 1:2 2:2 1`:
![](https://github.com/f-klubben/stregsystemet/assets/17174333/d5e826ed-9282-4857-af05-1f6d2902faec)

**Comment by BoAnd** [comment]
@krestenlaust: What is the problem? should tester 1:2 2:2 1:1 translate to 1:3 2:2?

**Comment by krestenlaust** [comment]
I originally labeled the issue wrongly. The idea is to have the purchase output formatted something along the lines of `tester har lige købt 3 Testøl og 2 kold kaffe` and the other example would be `tester har lige købt 25 øl`

**Comment by krestenlaust** [comment]
Sounds promising!
