### ISSUE TITLE
Can't migrate database on Windows without "c:/tmp" folder

### ISSUE THREAD

**Issue by krestenlaust** [f-klubben/stregsystemet#365]
I'm not entirely sure the issue is related to migration, it's probably related to django in general. Instead of trying to output error in a protected folder, it should just output the log file in a relative path.

**Comment by jonasKjellerup** [comment]
This is likely just a configuration issue. See the following file:
https://github.com/f-klubben/stregsystemet/blob/579edaa880c9db285a0114d8445710503c216f9d/treo/settings.py#L54
