### ISSUE TITLE
When you buy multiple (different) products at once, it complains that you should've used multibuy????

### ISSUE THREAD

**Issue by VinceUB** [f-klubben/stregsystemet#372]
What???
![image](https://github.com/f-klubben/stregsystemet/assets/25371789/b87345f8-ef33-4ba2-90c1-14c54e7787b0)

It complains when I write `username 1902 1910`?? And it tells me that I could've written `username 1902:3 1910`, when that would've bought me three times as many `1902`'s as I want??????? It feels like f-klubben is trying to cheat me into buying more... Shameful...

**Comment by krestenlaust** [comment]
The problem you're experiencing is actually that you've bought multiple times in a row (even though you've used multibuy for your last purchase)

But the issue actually exists:
![billede](https://github.com/f-klubben/stregsystemet/assets/17174333/e47b8b85-bae1-47b5-a6b4-5fffd68a6ba1)
