### ISSUE TITLE
Move purchase-heatmap category definitions to django admin panel

### ISSUE THREAD

**Issue by krestenlaust** [f-klubben/stregsystemet#375]
The definitions are hardcoded in the heatmap code, currently:
https://github.com/f-klubben/stregsystemet/blob/3bbf4d8d1d12c7496e9c6c5f4db86db3211557ba/stregsystem/purchase_heatmap.py#L136

**Comment by ha36d** [comment]
can I work on this one?

**Comment by jonasKjellerup** [comment]
> can I work on this one?

Go for it. I've assigned the issue to you.

**Comment by krestenlaust** [comment]
#448 superceeds
