### ISSUE TITLE
New requirements for sales management (Mega thread)

### ISSUE THREAD

**Issue by krestenlaust** [f-klubben/stregsystemet#385]
- [ ] Can the sales registration system log all actions in an electronic journal?
- [x] Does the electronic journal contain the same information as stated on the till receipt?
- [ ] Does the sales registration system have SAF-T as the default file format?
- [ ] Can the file be transferred electronically or read out on commonly available electronic media?
- [ ] Can the sales registration system generate a Z-report?
- [ ] Can the sales registration system generate an X-report?
- [x] Can the sales registration system automatically register payment using an electronic means of payment?
- [ ] Can the sales registration system record sales by means of payment used?
- [x] Does the sales registration system have a built-in calendar and clock?
- [x] Does the sales registration system have an associated printer function?
- [ ] Can the sales registration system print a till receipt that distinguishes between positive and negative amounts?
- [x] Can the sales registration system record sales separately for each seller? (Seller = Room)
- [ ] Can the sales registration system clearly mark on the till receipt whether it is a 'test receipt'?
- [ ] Does the sales registration system have features that allow information to be added, edited or deleted in the electronic journal (it is not allowed to)?

Source: https://skat.dk/en-us/businesses/new-requirements-for-electronic-sales-registration-systems-for-certain-sectors-in-2024

**Comment by jonasKjellerup** [comment]
As these requirements will come into effect starting the first of January. It may be relevant to prioritize figuring out how this project is going to make it to completion on time (or at least not super late XD).

I think some important first steps would be the following:

1) Get/create an overview of what is actually remaining and what is already built-in (just at a glance I can spot a few in your list that are already built-in, but remain unchecked - I'll include a list of the ones I've spotted further down in this comment).

2) Figure out what each of these requirements actually entails for our system. Currently the project as a whole is super difficult to get an overview of and take action on, which will likely deter many volunteers from helping with the project (on top of it already being a not very exciting project). Not only that, some requirements are very unclear in what capacity they apply to our system.

3) Acquire OCES3 certificates. We can't implement signing of transactions without this. We will likely want separate production and development certificates. This is likely a task for Forstyrrelsen as it requires MitId access for F-Klubben.

4) As per the [FAQ](https://skat.dk/media/zx1pji4o/ofte-stillede-spoergsmaal-faq-13.pdf?id=153989) from Skattestyrelsen, it is possible to request a script that can be used to test SAF-T reports. We may wish to do this. Although, a similar result can be achieved by using existing software to verify outputs using a XSD file (see below resources for link to the XSD).

# Creating an overview

I would recommend that each of the requirements are either rephrased/split to better express what they entail or that their descriptions are included in the list as some of the titles are a bit misleading.

(@krestenlaust) A mega thread, while useful for discussion, may not be the best way to organize this work. It can work if you manage to keep the original post up to date, but it may just be easier to manage elsewhere. If you want, I can see if I can find some time to set up a GitHub Project table/board for it.

## Completed tasks

I've noticed the following tasks that are complete, but aren't marked as such:

- "Can the sales registration system automatically register payment using an electronic means of payment?" - Electronic payments are the primary means of payment. And all such payments are recorded.
- "Does the sales registration system have a built-in calendar and clock?" - This is built-in, by virtue of running on a standard operating system. The only part that may be missing is:
  >  ... All adjustments of time indications in the system must be recorded in the electronic journal.

- "Does the sales registration system have an associated printer function?" - Per my understanding, this is only required if we don't send them digitally, which is what we would be doing.

The requirements "Can the sales registration system log all actions in an electronic journal?" is marked as complete, but its description entail a requirement that is not actually met by our system. 

> .. Transaction data in the electronic journal must be signed electronically with an OCES certificate identifying ..

This part of the requirement is not satisfied.

# Some questions that need to be resolved

There are some requirements that may or may not be complete, depending on how we interpret them. Some requirements may also be significantly larger in scope depending on how the requirements are interpreted. We need to get these ambiguities cleared up so we can determine how to proceed.

- What is considered a sale and what isn't. Is the purchase of "stregdollars" the sale or is it the use of "stregdollars" to buy something, or is it both? (I suspect @Zaph-x may have some insight regarding this)
  - Per my current understanding. This will affect whether we will have to include manual changes to stregdollar balances in the report, which would have to include information about the "employee" that performed this action.
  - It will also affect whether we will need to provide additional receipts, whenever an item is bough, as we currently only provide a receipt for the "purchase" of "stregdollars" (this receipt will also need to be modified a bit according to the legislation). 

(There are most definitely more questions that need to answered - but I've spent too long writing this already so I've forgotten most of them in the meantime... I'll make an edit if any of it comes back to me)

# Resources/links
- [Info page for suppliers of digital sales systems](https://skat.dk/erhverv/nye-krav-til-digital-salgsregistrering-for-visse-brancher-i-2024/for-leverandoerer-system-til-digital-salgsregistrering). Some useful links from the page:
  - [SAF-T XSD](https://skat.dk/media/xsupzyby/xsd-schema-definition-v12.zip?id=153982)
  - [Code list](https://skat.dk/media/p0ipq0mu/code_list_danish-saf-t-format-for-cash-register-data-v12.pdf?id=153981). List of ids/codes of various payment types, transaction types, etc.
  - [FAQ](https://skat.dk/media/zx1pji4o/ofte-stillede-spoergsmaal-faq-13.pdf?id=153989)
  - [SAF-T Technical description](https://skat.dk/media/fpaopncl/technical_description_danish-saf-t-format-for-cash-register-data-v12.pdf?id=153991)

**Comment by krestenlaust** [comment]
Forstyrelsen has decided on a meeting that this issue isn't relevant anyway, as we (according to them) don't fall under the new regulations🤷‍♀️

More time for developing interesting features instead :D
