### ISSUE TITLE
Update Python version to at least 3.10

### ISSUE THREAD

**Issue by krestenlaust** [f-klubben/stregsystemet#389]
The current version we're utilizing (3.6) reached [EOL](https://devguide.python.org/versions/) two years ago, having it updated along with the dependencies will make sure the Stregsystem will live long and prosper!

![Picture of python release cycle](https://github.com/f-klubben/stregsystemet/assets/17174333/f697bf46-9238-492b-a8f9-325bbd43392b)

**Comment by jonasKjellerup** [comment]
Since 3.8 will be EOL in < 1 year, would it not make more sense to target a version with a greater remaining support window?

**Comment by krestenlaust** [comment]
The reason I ended up with 3.8 is that the latest version of Pillow requires that version at least, and upgrading in small steps to the common denominator seemed easier. But I agree having a newer version would be better, which version would you suggest?

**Comment by jonasKjellerup** [comment]
Well, considering the fact that Python makes no forward or backwards compatibility guarantees, I don't really see any good rationale to make a choice based on, besides asking ourselves "How soon do we want to do this again?"

We can try to look at what the newest releases of our dependencies should support and use that. However this assumes that we will be updating all of our dependencies. Most of our dependencies are classified as "Python 3.11"  (or newer) on PyPi, but not all. Namely:

- `freezegun` is classified as 3.9. Latest PyPi release is Aug 12, 2022. Latest Github commit Feb 22, 2023.
- `qrcode` is classified as 3.10. Latest PyPi Release is Feb 5, 2023. Latest Github commit Feb 22, 2023.


So we may consider 3.9 as a minimum target, where all our dependencies should "just work" (assuming that they haven't had any breaking changes).

So i see three possible routes:
 - Target the newest release possible and deal with all the issue that come with that.
 - Target the minimum version that should be supported by the newest releases of all our dependencies (3.9).
 - Or lastly, increment vesions until something breaks and stop there. (Although I don't think we are going to make is very far).

With that said, if our goal is to keep Stregsystemet up to date with security support, then the greater issue is that we are using Django 2.2 which went EOL Apr. 1 2022 [(Django support support table)](https://endoflife.date/django). A upgrade to a new major version (3.2 LTS or 4.2 LTS) is more or less guaranteed to break plenty of things.

**Comment by BoAnd** [comment]
@jonasKjellerup what about PR: #409

**Comment by krestenlaust** [comment]
It looks like Freezegun supports 3.12 now
