### ISSUE TITLE
Userfriendly admin panels?

### ISSUE THREAD

**Issue by fishbacon** [f-klubben/stregsystemet#39]
Since we are not changing the stregsystem proper frontend ([this](https://kristopolous.github.io/BOOTSTRA.386/) and [this](http://code.steadman.io/telestrap/) still exists) maybe we should consider making the admin panel more user friendly. Making it easier for Treoen to use it day to day would be a great step I think.

**Comment by fishbacon** [comment]
I think there is a lot to be wanted from the process of creating several new members. Something like a spreadsheet would go a long way helping Treoen get that done quickly.

**Comment by DelusionalLogic** [comment]
I'm not opposed to changing the frontend, I don't know how the fembers will feel though.

Stuff like bulk creation of fembers, or bulk creation of payments, would probably be a welcomed addition. We'll have to speak with them to know what they do now, and how we can make it easier though.

**Comment by fishbacon** [comment]
> I'm not opposed to changing the frontend, I don't know how the fembers will feel though.
Strong opposition from all sides, including me, to changing the frontend. I have just been joking about changing it for so long.

**Comment by DelusionalLogic** [comment]
Then we wont ;)

**Comment by BoAnd** [comment]
@krestenlaust: Do you agree on closing this story? As I see it we have made many awesome improvements in the admin panel.

**Comment by krestenlaust** [comment]
Agree!

> @krestenlaust: Do you agree on closing this story? As I see it we have made many awesome improvements in the admin panel.

Agree!
