### ISSUE TITLE
Prosa's account doesn't work

### ISSUE THREAD

**Issue by JakobTopholt** [f-klubben/stregsystemet#395]
When attempting to buy something in the line system, with the account that Prosa (the union) has, an error message is displayed when attempting to access the account.

It will be assumed that you have admin access to figure out the username of the account.

When attempting to simply write the username so that you may access the interface for the account
![image](https://github.com/f-klubben/stregsystemet/assets/74545500/a302685e-53f3-4f42-81bf-e1d7c47ac0cf)

**Comment by JakobTopholt** [comment]
I'd be inclined to simply delete the account, and make a new one with the same name and balance, but it seems a hacky solution.

**Comment by krestenlaust** [comment]
I'll be looking into it some time today

**Comment by krestenlaust** [comment]
The account is simply deactivated. I'll be reinstated soon
