### ISSUE TITLE
Lower the limit for minimum amount paid into account

### ISSUE THREAD

**Issue by JakobTopholt** [f-klubben/stregsystemet#396]
Currently we have a minimum of 50 kroner for inserting money into your line account.

This limit was made back when Mobilepay charged a flat fee up to a very high amount, currently the fee seems to scale linearly with the amount of money inserted. To exemplify this, back in the day if 50 DKK were inserted the free would be (if memory serves me right) 0,60 DKK and if 500 were inserted it would also be 0,60 DKK. Currently it is "just" 1% of the total amount, meaning that we have no incentive to have people insert larger amounts into their account at a time.

Therefore it would be a good idea to lower the minimum amount of money inserted into the line account to e. g. 20 DKK rather than 50 DkK.

**Comment by joandrsn** [comment]
@krestenlaust, the fees have been changed as of 1. Oktober 2023 and are active now.
![image](https://github.com/f-klubben/stregsystemet/assets/5766695/0d92c26b-3d25-4796-923c-a83afa339456)


If you set the minimum to 20 DKK, then you would only be able to make 1-2 purchases before having to fill up again. I think people might be worse at remembering to pay for their drinks if they constantly have to refill their account, but it would have to be tested.

I don't know anything about bank transactions. Maybe @falkecarlsen can help here - or the current kassere.

**Comment by falkecarlsen** [comment]
https://www.mobilepay.dk/erhverv/fysiske-butikker/mobilepay-myshop#MyShop-priser

> pris per transaktion 0.99%

As @joandrsn picture shows, there is a ever-so-slight incentive to have higher payment limits due to rounding of the fee but that's insignificant. In reality we could set the minimum amount to whatever.

On the contrary, I don't see a good argument for why the minimum *should* be lower. Perhaps in the case of paying out an account when leaving the institute, but that's a lot of work on both parties for what is less than the price of a cup of coffee/cocoa.

**Comment by JakobTopholt** [comment]
I see that argument that there is not real benefit to a lower limit, the only one I see is that I wouldn't have to manually approve quite as many transactions below 50 DKK.

This might be a change having a similar amount of pros as cons.

**Comment by krestenlaust** [comment]
I've gone ahead and marked this as a skill-issue on Toppers part

**Comment by krestenlaust** [comment]
If we don't want to manually approve manual transactions, we could **replace it with a time penalty**. Alternatively, we could just have **automated shame mails**, and hope that will still disincentivize users from sending less than 50 kr.

Another argument for keeping the 50 kr limit is that the F-Club will have a more predictable/consistent liquidity that will compensate for the value tied to the wares stored in New Haven. If all members were to only pay to their account whenever they bought something, then we wouldn't have that 'loan' and the wares in New Haven would negatively impact the F-Club account.

For this reason, this isn't a matter for us to decide, bring it up for Forstyrrelsen. If you like the other proposals I brought up, then you're welcome to open a new issue.
