### ISSUE TITLE
It should be possible to adjust the time for an item in the kiosk

### ISSUE THREAD

**Issue by JakobTopholt** [f-klubben/stregsystemet#404]
Currently all pictures on the kiosk, sometimes referred to as the kiosk, have the same default amount of time which they're shown.

It would be nice to be able to increase the time for pictures which are text heavy.

They should probably default to the standard amount of time, but be able to be adjusted.

**Comment by krestenlaust** [comment]
Is it possible that your issue is covered by either of these issues? #362 #363 

Totally agree, I might look into this semester

**Comment by JakobTopholt** [comment]
It truly is, I should have looked up if the issue had already been created.
