### ISSUE TITLE
MobilePay Reporting API going out of support

### ISSUE THREAD

**Issue by jonasKjellerup** [f-klubben/stregsystemet#407]
MobilePay is in the midst of doing a transition to their new Vipps MobilePay platform. This means that the current implementation for fetching transactions will stop working come ~mid-2024.

The migration should in theory be fairly straightforward, but since we are still on the already deprecated V1 of the original API it may be more substantial, as the migration guides assume that we are on V3.

https://developer.mobilepay.dk/docs/reporting/transition-to-one-platform

![Reporttimeline-055fcc36eacd2e88ad6d036b34fc7d47](https://github.com/f-klubben/stregsystemet/assets/15014998/6f926bea-615d-44b8-a124-d65c864f90a1)

Migration information: https://developer.vippsmobilepay.com/docs/mp-migration-guide/reporting/
Documentation for the replacement API: https://developer.vippsmobilepay.com/docs/APIs/report-api/

**Comment by krestenlaust** [comment]
I can't quite figure out how to get access to their test environment 🤔

**Comment by jonasKjellerup** [comment]
I believe that we are using the "MobilePay MyShop" product, which isn't really intended to have any sort of integration. So, I unfortunately don't think there is a test environment for it.

I also found this in their documentation:

> Management API and Report API is not available in MT and can only be tested in production.

And this:

> Details for Denmark:
> 
> - Until launch in Denmark on March 12: The MobilePay Reporting API will work as before for Danish merchants.
> - After the launch in Denmark on March 12: The Vipps MobilePay Report API will include data for the MobilePay Reporting API.
> - After the launch in Denmark on March 12: The MobilePay Reporting API will not get new data for Danish merchants, but historical data for payments up until this date will be available until summer 2024.

So the in general what I'm hearing is: The integration breaks next week and you can't test until after it has broken.

**Comment by krestenlaust** [comment]
Yup, that's how I read it at first, I just figured that really wasn't the case, but it seems it is then...

**Comment by soupglasses** [comment]
> I can't quite figure out how to get access to their test environment 🤔

Docs are https://developer.vippsmobilepay.com/docs/APIs/report-api/ and then use the Norwegian test server at `https://apitest.vipps.no`. I feel almost 100% certain its literally just the Vipps API getting rebranded.

**Comment by krestenlaust** [comment]
I've been in contact with MobilePay about getting new API-keys. I ended up having to send an email, so I'm waiting for reply now.

**Comment by krestenlaust** [comment]
We've gotten a confirmation from MobilePay, that they do not provide API-keys to regular sellers (<What we are>) anymore, only registered bookkeeping software can be accepted into their 'accounting partner'-programme, and receive API-keys.

I've written an email to get the Stregsystem registered as a bookkeeping software and possibly become an accounting partner, but I don't expect them to actually do so. Even if they do, there's probably a stark fee/membership. We'd have to be our own accounting partner in that sense too.

We are currently looking into different payment gateway services, to replace the direct MobilePay reporting access, with an actual payment gateway. This will be more costly than before, and will require a whole new implementation.

**Don't expect services to be restored soon, make use of the manual refill opportunities provided at the institute in the meantime**

**Comment by krestenlaust** [comment]
It seems like, it will be possible to have our system registered as a bookkeeping software with Vipps/MobilePay! We're still waiting for confirmation, but hopefully it succeeds. As soon as the API-key has been acquired it will be possible to continue the implementation #416

**Comment by krestenlaust** [comment]
We've got keys baby! Expect to see more updates in #416

**Comment by krestenlaust** [comment]
I'm planning to deploy later today, and we should know by tomorrow whether it works or not in prod
