### ISSUE TITLE
Tea in the rank list 

### ISSUE THREAD

**Issue by VinceUB** [f-klubben/stregsystemet#414]
Why is there no tea in the rank list:( 
Would be nice if there was tea in the rank list.
(It would be the only category I actually have a chance of getting anywhere on)

**Comment by krestenlaust** [comment]
Feel free to dive in. Let me know if you need more pointers!

The template file related:
https://github.com/f-klubben/stregsystemet/blob/af0efd806ae743b0e8a9639376c4a31b81d61cd2/stregsystem/templates/stregsystem/menu_userrank.html

The view procedure which does the rendering:
https://github.com/f-klubben/stregsystemet/blob/af0efd806ae743b0e8a9639376c4a31b81d61cd2/stregsystem/views.py#L266-L331

**Comment by JakobTopholt** [comment]
How is it going @VinceUB ?

**Comment by VinceUB** [comment]
P4 is going...

**Comment by JakobTopholt** [comment]
Is P4 still going @VinceUB ?

**Comment by VinceUB** [comment]
Funny story, we actually finished the entire program last Friday and are planning to go through the report a final time tomorrow before we hand in, so I'll start work after that.

I AM JOKING. P4 IS NOT OVER. IT IS STILL GOING. Funny how it takes more than a month to learn about, plan out, write, and describe an interpreter for a custom language.

**Comment by krestenlaust** [comment]
Solved thanks to @BoAnd's advice
![billede](https://github.com/f-klubben/stregsystemet/assets/17174333/02753565-d005-4e0e-a5c5-985088b2e7da)

Should Fuzetea (icetea) be in the category? @VinceUB
