### ISSUE TITLE
Refund sale

### ISSUE THREAD

**Issue by krestenlaust** [f-klubben/stregsystemet#418]
Option to refund a sale (delete it and add the amount back into the account) and return a payment (delete it and subtract the amount from the account)

**Comment by TheRumle** [comment]
I might take a look at this

**Comment by krestenlaust** [comment]
Finders keepers 🙏

**Comment by JakobTopholt** [comment]
👀 He took a look at it

**Comment by JakobTopholt** [comment]
Perhaps this feature should be extended to the way "delete sale" works, as it seems intuitive for most people, that the deletion of a sale should also incur a refund (a balance adjustment)?

**Comment by krestenlaust** [comment]
I don't think we can (or even should) change the way 'delete' works. That would make a fundamental CRUD-operation inconsistent
