### ISSUE TITLE
Bread razzia page for TREO

### ISSUE THREAD

**Issue by Rene4100** [f-klubben/stregsystemet#43]
Currently, when TREO are doing bread razzia we have to go into the stregsystem admin page, to validate a fember. This is not suitable since normal fembers can, "slight of hand" change information about themselves or other fembers, while the TREO menber i busy checking the other people passing by.
Therefore it could be good to have a simple page where we can do the validation of fembers.
It needs a text input field - and a validate button
When a user presses the button then, a big green checkmark together with info about the fember, Firstname, Lastname, and balance, has to be shown.
If the user does not exist in the stregsystem, then a big red X is shown together with a text indicating that the user is not a member or found in the stregsystem

**Comment by jones-g** [comment]
An added feature should be to validate if a username has already been typed in. Right now two different people could type in the same username and be validated. However as with many things in F-klubben this system also relies on trust :)

**Comment by ThomasPilgaard** [comment]
This feature could be generalized to not only validate if a user is a member, but also check if a user have bought a specific thing in Stregsystemet, e.g. FLAN or FLAN aftensmad. We at FLAN have to do the same way of checking if a user have bought an item from Stregsystemet with a big list in the admin page.

**Comment by VirtualSatai** [comment]
Please see #44.

If you want to check whether or not a name have been entered recently, then you'd have to use some kind of storage or AJAX maybe. #44 should be fine as a first version imo, then the TREO can request more if they feel like it.

**Comment by DelusionalLogic** [comment]
We'd love to increase the scope of the feature as we go forward, but for now what can be seen in #44 is a great improvement to at least one workflow. There's more to be done, but it's surely a great first step.
