### ISSUE TITLE
Make userdata available

### ISSUE THREAD

**Issue by krestenlaust** [f-klubben/stregsystemet#435]
Having the ability for a user to request an email with their data would be cool

**Comment by krestenlaust** [comment]
I think it's easiest to only offer it by e-mail. Not sure how it works when sending emails with attachments from a local server

**Comment by Mast3rwaf1z** [comment]
I don't know whether it's possible, but I put up the pr for research purposes

**Comment by krestenlaust** [comment]
I'm pretty curious as for how much can be done through django, like file management, removing generated files after timeout etc.

**Comment by Mast3rwaf1z** [comment]
> I'm pretty curious as for how much can be done through django, like file management, removing generated files after timeout etc.

I don't think generating files is needed, (without knowing) i would assume that smtp works like http such that i can just send a byte stream and call that a csv. I don't see the need of writing the database into a file to then read that file back into memory.

**Comment by krestenlaust** [comment]
I just guessed it worked as a link. Either way, it needs to be stored somewhere, I'm not sure for how long it will be stored on the sender server 🤔
