### ISSUE TITLE
Header off-center because of buttons

### ISSUE THREAD

**Issue by krestenlaust** [f-klubben/stregsystemet#478]
Most likely unrelated to this PR (but I discovered it just now)
#297 adds another button in the top, which causes the title to be off-center, do you have a good fix?
![billede](https://github.com/user-attachments/assets/d4eef6ba-1a26-435f-906c-dae85a802f3d)

_Originally posted by @krestenlaust in https://github.com/f-klubben/stregsystemet/issues/475#issuecomment-2313268959_

**Comment by BoAnd** [comment]
We could rewrite the **table** to **div** instead. And then use **display: grid** like this (https://github.com/f-klubben/stregsystemet/commit/b3e2ef99cead851ae2a8546cd5a08f5c57582736)

**Comment by JakobTopholt** [comment]
Literally unusable, I can never unsee this
