### ISSUE TITLE
When illegal e-mail is submitted, there is no possibility to fix it

### ISSUE THREAD

**Issue by VinceUB** [f-klubben/stregsystemet#501]
So, let's say my name is Test Example, my e-mail address is test@example.com, and my gender is unknown (optional). 

I hear about the F-club, and I'm like "Wow! I want to be part of this!" So I go to sign up, and my page looks like this:
![image](https://github.com/user-attachments/assets/a74a801b-8422-4644-8712-531a6c5830f5)

I press "Tilmeld", but _OH NO!!!!!_ I typed `"` instead of `@` because I applied with the computer on the Beach Road (Strandvejen) and the keyboard layout there is Danish (puke emoji), not US.

![image](https://github.com/user-attachments/assets/ed650701-7a6d-43b4-8679-d44a34583101)

Now, there is an error, and it asks me to type in a valid e-mail address. But there is no input field for me to type in. So the only way for me to sign up, is by going back to the main menu. I get very frustrated and decide that not only do I not feel like joining the F-club anymore, but I also outright despise it now. Therefore, I make it my ultimate mission to destroy the F-club once and for all, for having embarassed my like this.

**To avoid the demise of the F-club, make it possible to resubmit an e-mail address correctly**

**Comment by VinceUB** [comment]
Wait no, there is an input. My bad.

**Comment by atjn** [comment]
Yeah it is not very intuitive that the input is moved underneath the error message. I plan on revisiting this form sometime in the future to see if we can improve it.

**Comment by atjn** [comment]
Feel free to open a new issue about how unintuitive it is.

**Comment by krestenlaust** [comment]
Sikke en tråd at vågne til
