### ISSUE TITLE
Allow users to enter their usernames in other case sensitivities

### ISSUE THREAD

**Issue by patrickreiffenstein** [f-klubben/stregsystemet#503]
Currently, when a user is using the stregsystem to access their profile, if their casing is wrong it will result in a page telling them that there is no user.

Example picture for the user 'tester' with 'Tester' having been used as input:
![image](https://github.com/user-attachments/assets/ae17bc23-1842-4e25-b156-d9acb98799e3)

I believe it would be better if it worked in a way so that 'tester' could use their account with whatever casing they want, such as 'TeStEr'. It is already not possible to add another user with same name but different casing, so this shouldn't result in usernames conflicting. 

Shoutout to @phutsorn for initially finding this.

**Comment by krestenlaust** [comment]
This is a weird bug which seems to only be present some places. Have you tried varying the casing on Prod? Mine still worked
