### ISSUE TITLE
Accounting - Cron job

### ISSUE THREAD

**Issue by ghost** [f-klubben/stregsystemet#53]
**The first day in each month 00:01** 
- Post the total amount of sale for the month before to dinero using the dinero API. 
- Post the information from all payments sessions for the month before to dinero using the dinero API. 
- For all users with a balance > 0 and no sales in x years, add a negative sale of the product: expired equal to the balance.  

**1/1 00:02 each year:** 
- Send an email to regnskab@fklub.dk with the total balance for all active members. 

**1/7 00:02 each year:** 
- Send an email to regnskab@fklub.dk with the total balance for all active members.

**Comment by jacobelefsen** [comment]
I have some examples of the API calls to dinero. However, these things can not be tested without me or our treasurer.

**Comment by fishbacon** [comment]
Please send and email to FIT about cron jobs you would like to have made for the F-klub server, this repository is for Stregsystem development.

We could make an endpoint for generating this data but I imagine using django for it is silly since an SQL should be fine.

**Comment by fishbacon** [comment]
> I have some examples of the API calls to dinero. However, these things can not be tested without me or our treasurer.

I cannot imagine this is true, if we assume the dinero API follows the documentation on their website/github I am sure we can test everything by stubbing them.

**Comment by fishbacon** [comment]
> For all users with a balance > 0 and no sales in x years, add a negative sale of the product: expired equal to the balance.

This looks like a feature request, I do not understand it but it looks like it.

**Comment by jacobelefsen** [comment]
The cron jobs is related to the rest of the issues. 

FIT can not access our dinero account. 

> This looks like a feature request, I do not understand it but it looks like it.
This is for handling of expired balance

**Comment by fishbacon** [comment]
> The cron jobs is related to the rest of the issues.

So you do want an endpoint which generates this data. Okay.

> FIT can not access our dinero account.

I am confused, how does what I said require FIT to access dinero? Please explain why we need access to dinero to integrate with their api (which from what I can find seems to be documented)

>>>For all users with a balance > 0 and no sales in x years, add a negative sale of the product: expired equal to the balance.

>> This looks like a feature request, I do not understand it but it looks like it.

> This is for handling of expired balance

I read it as removing all money from a person after some time of inactivity. I am not sure this is intended or something we would want to do. 

Please if you have several things you want to suggest make several issues. We can handle it.

**Comment by jacobelefsen** [comment]
A django shell script is fine.
You don't need access, but you need some Domain knowledgde at least. 
 It's not a decision for FIT..

**Comment by fishbacon** [comment]
> A django shell script is fine.

I do not follow.

> You don't need access, but you need some Domain knowledgde at least.

Are we protecting this domain knowledge from being shared? Is bookkeeping too hard for our contributors to understand? Is it like the language of cthulu impossible to pronounce and needs a young priest and an old priest? Explaining the desired outcome and I imagine someone can implement it.

> It's not a decision for FIT..

I mean, whoever implements it ultimately decides that it is important enough to implement. As you know.

Please be more clear in your requests and provide reason for things which are not something obviously a good idea. See issues by @jones-g for examples of issues which provide good explanation (some are on the other, now defunct implementation).

**Comment by jacobelefsen** [comment]
I will produce an official document after our next meeting. This is too time consuming.

Den 30. apr. 2017 9.45 PM skrev Mark Faldborg <notifications@github.com>:

A django shell script is fine.

I do not follow.

You don't need access, but you need some Domain knowledgde at least.

Are we protecting this domain knowledge from being shared? Is bookkeeping too hard for our contributors to understand? Is it like the language of cthulu impossible to pronounce and needs a young priest and an old priest? Explaining the desired outcome and I imagine someone can implement it.

It's not a decision for FIT..

I mean, whoever implements it ultimately decides that it is important enough to implement. As you know.

Please be more clear in your requests and provide reason for things which are not something obviously a good idea. See issues by @jones-g<https://github.com/jones-g> for examples of issues which provide good explanation (some are on the other, now defunct implementation).

**Comment by jones-g** [comment]
Hmm I am not certain about the idea of wiping members balance after some period. This had never been done before. @mchro do you know if we are even allowed to do this?

**Comment by jacobelefsen** [comment]
You must do it in relation to Danish legislation. This is not a discussion for a public Github discussion. -> SLACK 
________________________________________
Fra: Jonas G [notifications@github.com]
Sendt: 3. maj 2017 09:38
Til: f-klubben/stregsystemet
Cc: Jacob Elefsen; Author
Emne: Re: [f-klubben/stregsystemet] Accounting - Cron job (#53)

Hmm I am not certain about the idea of wiping members balance after some period. This had never been done before. @mchro<https://github.com/mchro> do you know if we are even allowed to do this?

**Comment by DelusionalLogic** [comment]
So, this doesn't seem very difficult. If anyone is interested in picking it up heres my thoughts:

- Make a new app to handle the talk with the accounting system.
- Make a stub library mapping function calls to dinero posts 1 to 1. (To make it possible to mock in tests)
- Add a field to the Sales to keep track of if they have been submitted to accounting
- Add a manage.py command to submit to accounting.
  - When this is run just go through all sales which have not been accounted and do so, while marking them as accounted.
- This is obviously pretty important functionality, so be sure to test everything thoroughly.
  - I don't think testing the stub library is important, since that will just be filled with http REST requests.

We could then add the manage.py command to systemd to make sure it's run when we want to, but i think we should integrate as much as possible inside django.

I'd prefer separating this feature from the two other cron jobs, both by admin command, as well as by pull requests.

**Comment by jacobelefsen** [comment]
Part of this issue is almost done at my local server. 

The cron jobs for emails and expired balance is still missing.

**Comment by BoAnd** [comment]
To old issue. If accounting is missing this feature then create a new issue.
