### ISSUE TITLE
Payments sessions

### ISSUE THREAD

**Issue by ghost** [f-klubben/stregsystemet#56]
- A payment session is used for our Friday's payment. 
- Payments sessions consist of a list of payments.
- Each payment has a user, amount, source (Only card and cash).
- The payment sessions also have the following properties: user (The current user), received on  card (amount), received in cash (amount), date/time, the number of new members.
- If the payment to a user is the first payment for the user, the balance must be adjusted as (balance = balance + (amount-200) and the number of new members + 1.

**Comment by fishbacon** [comment]
This looks like it could be related to #39. We might want to make a label for these improvements and suggestions.

**Comment by fishbacon** [comment]
The last point seems like a separate thing from the rest of this issue, could you write an issue for it instead of having it here?

**Comment by fishbacon** [comment]
I imagine this could all be solved by having a reporting page like sales and ranks just for payments.

The request seems to be tangentially related to one of the suggestions in #54 since because of the cash/card thing.

**Comment by jacobelefsen** [comment]
A reporting page is not sufficient. A payment session must save some information. The last point is not a  separate thing.

**Comment by fishbacon** [comment]
> A reporting page is not sufficient. A payment session must save some information. 

What information you are not giving anything here.

> The last point is not a separate thing.

Explain why it is not. Just saying so does not make me understand why.

**Comment by jacobelefsen** [comment]
How will you handle unique payment sessions on a reporting page? And how to related payment to a session?

Because for each payment, if the user is new they have to pay for the membership and you have to save the number of new members.

**Comment by fishbacon** [comment]
> How will you handle unique payment sessions on a reporting page? And how to related payment to a session?

The date should suffice, are people running several "payment sessions" in a single day? Please provide a use case.

> Because for each payment, if the user is new they have to pay for the membership and you have to save the number of new members.

Both members and payments should be timestamped, I agree, we need to fix the member model. Number of new members is pretty simple to find from a timestamp and a count.

**Comment by jacobelefsen** [comment]
Yes, the date is not sufficed. 

All the things described in my original is based on how the TREO make the payment sessions today and how the rules are in Denmark.

**Comment by fishbacon** [comment]
Provide an example of why the date does not suffice.

**Comment by jacobelefsen** [comment]
Because some days the card terminal is used 3 times without any relation. This is 3 different sessions.

Den 30. apr. 2017 9.47 PM skrev Mark Faldborg <notifications@github.com>:

Provide an example of why the date does not suffice.

**Comment by fishbacon** [comment]
So you did not read what I wrote? That is depressing.

I said:
> The date should suffice, are people running several "payment sessions" in a single day? Please provide a use case.

**Comment by fishbacon** [comment]
> Because some days the card terminal is used 3 times without any relation. This is 3 different sessions.

Okay, that gives us somewhere to work from. The feature request seems reasonable but maybe give a reporting page a chance and then if that does not work we can get into adding sessions?

**Comment by jacobelefsen** [comment]
Each time a member of the Treo use the card terminal we need some documentation in dinero. Today we manuel do this using Google drev. Some days we make 3 session and also 3 spreadsheets in Google drev.

Den 30. apr. 2017 10.03 PM skrev Mark Faldborg <notifications@github.com>:

So you did not read what I wrote? That is depressing.

I said:

The date should suffice, are people running several "payment sessions" in a single day? Please provide a use case.

**Comment by fishbacon** [comment]
I still suggest you make this part:

> If the payment to a user is the first payment for the user, the balance must be adjusted as (balance = balance + (amount-200) ...

a separate issue since it does not seem to relate to sessions and might possibly be a simple change.

**Comment by BoAnd** [comment]
@krestenlaust: Should we not close this one? I think nobody knows what to do with this issue.

**Comment by krestenlaust** [comment]
> @krestenlaust: Should we not close this one? I think nobody knows what to do with this issue.

Yes, agree!
