### ISSUE TITLE
Whitespace cleanup

### ISSUE THREAD

**Issue by fishbacon** [f-klubben/stregsystemet#57]
Since I keep committing whitespace changes someone should go through and cleaning up whitespace.

I am talking about /t after functions and inconsistent tab/space between files.

**Comment by fishbacon** [comment]
For now adding `?w=1` to any view with changes will remove whitespace in github.

**Comment by fishbacon** [comment]
![image](https://cloud.githubusercontent.com/assets/276945/26013956/d9b51f68-375a-11e7-8974-41f5a4bf53d4.png)

`pylint` does not like our code.

**Comment by DelusionalLogic** [comment]
Well to be honest, I'd probably rate the code 2/10 on a good day.

**Comment by fishbacon** [comment]
Seems to largely be fixed now. Closing.
