### ISSUE TITLE
Razzia wizard

### ISSUE THREAD

**Issue by fishbacon** [f-klubben/stregsystemet#58]
Someone suggested that the razzia feature was simply too much to bare and that is why we should extend it severely.

I suggest making a razzia wizard, giving the persons who are wanting to check something with regards to members and purchases ample ability to do so.
My suggestion is to create a page where the TREO can enter several products which they want to check, and a title for their razzia. 
More features like max number of re-entries and an error/success message template would also make the experience much nicer. 
A nice-to have would be a model for razzias so that they can be reused, e.g. bread razzia, but I see it as optional.
I imagine the whole thing can be build in a few hours.

**Comment by fishbacon** [comment]
It was suggested for there to be a wizard in the wizard:
http://orig04.deviantart.net/c3e3/f/2016/042/5/0/you_re_a_wizard__barry__by_blazbaros-d9r74qv.png

**Comment by VirtualSatai** [comment]
I think this would be a good addition, since it would empower usage for F-Lan, as asked by in #43: https://github.com/f-klubben/stregsystemet/issues/43#issuecomment-295180721 

However we need the approval of the all-mighty Forstyrrelse before we develop and deploy such a breaking feature ;)

**Comment by DelusionalLogic** [comment]
@VirtualSatai Has begun working on this.
