### ISSUE TITLE
pylint is super unhappy

### ISSUE THREAD

**Issue by fishbacon** [f-klubben/stregsystemet#60]
Since we have not agreed on any guidelines for the project I went with default settings for pylint and ran it on our code.

We get a score of 0.09/10 when I run `pylint *` from root. That is not impressive.
I have created a pep8 branch in which I will be going though the project and making pylint happy.

My first goal was to make `pylint --disable=all --enable=c0303 *` happy and it is as of #59.

**Comment by fishbacon** [comment]
We should also make a pylintrc file for stuff we can agree is good.
http://pylint-messages.wikidot.com/all-codes for codes.

**Comment by fishbacon** [comment]
Okay, after installing `pylint-django` the project score jumped to 4.20 so that's nice.

**Comment by VirtualSatai** [comment]
Aint no more fam.
