### ISSUE TITLE
Unittest old code

### ISSUE THREAD

**Issue by fishbacon** [f-klubben/stregsystemet#61]
Since I started working on making pylint happy with the project in #60, I found that we should probably have tests for the old parts of the code so that refactoring and moving stuff around does not turn into a nightmare.
This would also go a long way ensuring that functionality does not change.

**Comment by DelusionalLogic** [comment]
We've started doing this for new code. The hope is that as time progresses we'll replace the old code and write tests naturally.

We've just set up some travis-ci and coveralls to hopefully encourage more tests!

**Comment by fishbacon** [comment]
> We've started doing this for new code. The hope is that as time progresses we'll replace the old code and write tests naturally.

Replacing the code and then testing it is not good enough, we need the code to do the same things. As per our long discussions on the mailing list years and years ago.

**Comment by DelusionalLogic** [comment]
We are doing it the other way around. When we change something we first look at how it's done now. Then we write code that we think is functionality equivalent, and then we test that the new code conforms to way the old code did it. We don't intend to introduce any user facing regressions.

Currently we have tests for the core functionality of buying stuff, as well as some more backend facing things.

**Comment by DelusionalLogic** [comment]
So I looked though some of the things we aren't covering, as reported by coveralls. I have to say some of the things we aren't covering is pretty low hanging fruit, so I'm going to change my flip here and say that I'm going to be focusing on getting those easy places tested and getting the code coverage up in the next couple of versions.

**Comment by DelusionalLogic** [comment]
Work has begun in #76
