### ISSUE TITLE
Filter on Activated products

### ISSUE THREAD

**Issue by Rene4100** [f-klubben/stregsystemet#62]
To make it easier to disable products which either are out of stock or not for sale (e.g. events or Fadøl) I would like to be able filter on activated and deactivated products. 

Currently, I can only filter products based on deactivate date, and price

**Comment by DelusionalLogic** [comment]
I see. That should be easy.

**Comment by VirtualSatai** [comment]
This is clearly a **feature** and it should be approved by the almighty "Forstyrrelse". Send an e-mail to them for approval and then we can start developing the feature.

**Comment by fishbacon** [comment]
> This is clearly a feature and it should be approved by the almighty "Forstyrrelse". Send an e-mail to them for approval and then we can start developing the feature.

A committe shall be drafted and four primary sources of this requirement found.

**Comment by VirtualSatai** [comment]
Fixed in  #66
