### ISSUE TITLE
Invoice generator / maker

### ISSUE THREAD

**Issue by Rene4100** [f-klubben/stregsystemet#77]
I have in the summer holiday been asked to provide an overview for some of our Fembers' sales.
At that time, I searched the sales for the given user, and then copied and pasted the results into an excel sheet. 
But that is not viable in the long-term, and also not an accepted "legal" solution as there are some information that are needed to make it a "legal" invoice.
The invoice generator would also make it much easier for the Treo to handle sales to our partners, i.e. the institute. 

So the system should be able to create an invoice for paid goods, found in the sales database, but also for stuff that has not yet been paid for instance sales to AAU.

**Comment by VirtualSatai** [comment]
Can you provide an example of how such an invoice would look like?

**Comment by Rene4100** [comment]
It could be like this https://www.hurtigfaktura.dk/assets/faktura-4f9dae509fe2fd5104ed59fe4246f1961b161d4baf3e18c8157216e2d5783ff7.png
That site also has a way to easily do it, but still require a lot of work 
https://www.hurtigfaktura.dk/faktura-skabelon

**Comment by DelusionalLogic** [comment]
That interesting, but it seems like something that could be handled by the accounting software we use, and maybe should since that has all the certifications.

The stregsystem doesn't know anything about bulk orders after all. I suppose it could, but that seems like a lot of work.

**Comment by jones-g** [comment]
Invoices should be handled by the accounting system. I may be unaware of the workflow but to my knowledge we either send an invoice or use stregsystemet as payment. Not both. That would mean that someone used their stregkonto to pay and then we send an invoice causing a double payment?

It might be necessary for more than the F-klubben accountant to have access to create invoices in the accounting system or a agreement must be made with him/her about how this should be done.

**Comment by fishbacon** [comment]
This sounds like a fully different product than Stregsystem, I am closing this issue :)
