### ISSUE TITLE
Add category to products 

### ISSUE THREAD

**Issue by Rene4100** [f-klubben/stregsystemet#78]
For now, when new products are added to the Stregsystem you(FIT) have to manually the rankings found in report/ranks/ this could be done easier by adding categories to the products.

I know it might be a lot of work to update the old products with a category, but I am willing to help out with it.

**Comment by VirtualSatai** [comment]
I think this is doable in a reasonable way, without much hassle. I image that some items would be part of multiple categories. (Category <-> Product is a many-to-many) relation. I will take a look at it soon (tm).

Can you imagine any other places, than the sales ranks, where this could be relevant?

**Comment by fishbacon** [comment]
Started over here: https://github.com/f-klubben/stregsystemet/tree/feature/product-categories

**Comment by VirtualSatai** [comment]
Since this is merged, and the remaining points on the list is enhancements, I'll close the issue.
