### ISSUE TITLE
Send email to Fember when MobilePay payment has been processed

### ISSUE THREAD

**Issue by Rene4100** [f-klubben/stregsystemet#81]
Currently, we are having a lot of fembers asking if their money has been placed on their account.

This could be done easier, by sending an email to the given fember, when the TREO / Jacob adds a payment when the money is received from MobilePay.

**Comment by VirtualSatai** [comment]
I think this would be a good improvement. It would require us to record what type of payment it is (or rather if it should alert the fember). We'd have to figure out how e-mails sent from using django works too.

**Comment by jones-g** [comment]
An idea could be that users can opt in and out of notifications for payments. I mean even Friday payments aren't instant some people might like to know when their funds are available.

There could be to tiers of notifications. An "instant" which could be Friday payments with cash or credit card and "delayed" such as Mobilepay and wire transfer.

**Comment by fishbacon** [comment]
What are our options when it comes to SMS? Could we look into that? Maybe twillio or something.

**Comment by fishbacon** [comment]
> We'd have to figure out how e-mails sent from using django works too.

I have never done it but from [this](https://docs.python.org/2/library/email-examples.html) it looks pretty simple. Maybe even [this](https://docs.djangoproject.com/en/1.11/topics/email/)?

The opt out feature might be really hard to do since we don't really have a way to do user configuration other than them emailing the admins.

**Comment by jones-g** [comment]
The opt out feature could actually be make the "want spam" field have a use!

Just enable it for all people and give them a link in the mail to unsubscribe. Simple url end point taking a username, perhaps a random key and then disable if the user clicks it.

**Comment by fishbacon** [comment]
Was the want spam field not introduced because lecturers were not interested in receiving emails about fyttetur? Overloading it for this use might be a bad idea.

However I do like the idea of making opt out a link in the email.

**Comment by jones-g** [comment]
I was told that the field is not used for anything!

**Comment by fishbacon** [comment]
I am not sure it is currently being used for that, just that it used to be that so overloading it would make a historic field more pedestrian.

**Comment by mchro** [comment]
Was/is used by the script that populates the fembers mailing list. It is a closely guarded secret, and I believe only one "lecturer" has it disabled.

**Comment by DelusionalLogic** [comment]
>It is a closely guarded secret

Not anymore it isn't.

On a serious note. I think this would be useful!

**Comment by mchro** [comment]
The reasoning was more that it should not be possible to not receive fembers mails, if one wants to use stregsystemet.

**Comment by Rene4100** [comment]
On the other hand, it could properly be good to know if the payment is just a regular payment made with cash or card (which does not require a mail) or a payment made with MobilePay.

**Comment by BoAnd** [comment]
There is now an implementation in stregsystem, There sends mail to the user. https://github.com/f-klubben/stregsystemet/pull/144.
Should we close this issues or should it still be open ?

**Comment by VirtualSatai** [comment]
I'm gonna close it now, if anyone have ideas for improvement to the implementation in #144 they're welcome to make a new issue, or create a PR.
